#!/bin/bash

# Authentication Flow Test Script
# This script helps you test the login and signup flows

echo "================================================"
echo "Authentication Flow Testing Guide"
echo "================================================"
echo ""

# Check if backend is running
echo "1. Checking if backend is running..."
if curl -s http://localhost:8000/health > /dev/null 2>&1; then
    echo "   ✓ Backend is running on http://localhost:8000"
else
    echo "   ✗ Backend is NOT running!"
    echo "   Please start the backend first:"
    echo "   cd anzavillagebackend && python run_dev.py"
    exit 1
fi

echo ""
echo "2. Backend endpoints check:"
echo "   - POST /auth/send-code (login)"
echo "   - POST /auth/verify-code (login)"
echo "   - POST /auth/send-signup-code (signup)"
echo "   - POST /auth/verify-signup-code (signup)"
echo "   - POST /auth/setup-profile (profile completion)"

echo ""
echo "================================================"
echo "Manual Testing Steps"
echo "================================================"
echo ""

echo "TEST 1: Login with Unregistered Email"
echo "--------------------------------------"
echo "1. Go to http://localhost:5173/login"
echo "2. Enter a non-existent email (e.g., newuser@test.com)"
echo "3. Click 'Continue with Email'"
echo "4. Expected: Toast notification 'Email not registered. Please sign up first.'"
echo "5. Expected: Action button to navigate to signup"
echo ""

echo "TEST 2: Signup with New Email"
echo "-----------------------------"
echo "1. Go to http://localhost:5173/register"
echo "2. Enter a new email (e.g., test@example.com)"
echo "3. Click 'Send Code'"
echo "4. Expected: Toast notification 'Verification code sent to your email'"
echo "5. Check backend terminal for the verification code"
echo "6. Enter the 6-digit code"
echo "7. Expected: Toast 'Email verified successfully!'"
echo "8. Expected: Profile setup dialog appears"
echo "9. Fill in profile details and submit"
echo "10. Expected: Toast 'Welcome! Your profile is complete.'"
echo "11. Expected: Redirect to dashboard"
echo ""

echo "TEST 3: Signup with Existing Email"
echo "----------------------------------"
echo "1. Go to http://localhost:5173/register"
echo "2. Enter an email that already exists"
echo "3. Click 'Send Code'"
echo "4. Expected: Toast 'Account already exists. Please login instead.'"
echo "5. Expected: Action button to navigate to login"
echo ""

echo "TEST 4: Login with Registered Email"
echo "-----------------------------------"
echo "1. Go to http://localhost:5173/login"
echo "2. Enter an existing email"
echo "3. Click 'Continue with Email'"
echo "4. Expected: Toast 'Verification code sent to your email'"
echo "5. Check backend terminal for the verification code"
echo "6. Enter the 6-digit code"
echo "7. Expected: Toast 'Login successful!'"
echo "8. Expected: Redirect to dashboard (or profile setup if profile incomplete)"
echo ""

echo "TEST 5: Invalid Verification Code"
echo "---------------------------------"
echo "1. During login or signup code verification"
echo "2. Enter an incorrect 6-digit code (e.g., 123456)"
echo "3. Expected: Toast 'Invalid verification code'"
echo "4. Expected: Code input cleared"
echo ""

echo "TEST 6: Code Resend"
echo "------------------"
echo "1. During code verification step"
echo "2. Click 'Resend' button"
echo "3. Expected: Toast 'Code resent to your email'"
echo "4. Expected: 60-second cooldown timer starts"
echo ""

echo "================================================"
echo "Debugging Tips"
echo "================================================"
echo ""
echo "If you see 400 Bad Request errors:"
echo "1. Check backend terminal for detailed error messages"
echo "2. Open browser DevTools → Network tab"
echo "3. Look at the request payload and response"
echo "4. Check if email validation is failing (must be valid EmailStr format)"
echo "5. Verify CORS is configured correctly in backend"
echo ""
echo "Common Issues:"
echo "- Backend not running: Start with 'cd anzavillagebackend && python run_dev.py'"
echo "- Wrong API URL: Check .env has VITE_API_URL=http://localhost:8000"
echo "- CORS errors: Check backend CORS settings allow http://localhost:5173"
echo ""
echo "================================================"
echo "Files Modified"
echo "================================================"
echo "- src/services/auth.ts (enhanced error handling)"
echo "- src/pages/LoginPage.tsx (added toast notifications)"
echo "- src/pages/RegisterPage.tsx (added toast notifications)"
echo "- src/pages/ProfileSetupPage.tsx (NEW - profile completion)"
echo "- src/lib/router.tsx (added /profile-setup route)"
echo ""
echo "See AUTH_FIXES.md for detailed documentation"
echo "================================================"
